on: pull_request

permissions:
  pull-requests: write
jobs:
  dependabot:
    env:
      PR_NUMBER: ${{ github.event.number }}
      REPO_NAME: ${{ github.repository }}
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
    - name: Auto merge the PR
      run: gh pr merge --auto --rebase --repo $REPO_NAME  $PR_NUMBER
      env:
        GH_TOKEN: ${{ github.token }}

    
